install:
- sudo apt-get update
- sudo apt-get install tree
- source ./ci/texlive_install.sh
cache:
  directories:
  - /tmp/texlive
  - $HOME/.texlive
script:
- l3build unpack
- tree -a .
- l3build doc